### ISSUE TITLE
modifiers not working correctly?

### ISSUE THREAD

**Issue by tcurdt** [atomicgo/color#1]
This works as expected:

```
echo -e "\033[4mfoo\033[0mbar"
```

But this does not give the same result:

```
	typed := color.NewStyle(nil, nil, color.Underline).Sprint
	completed := color.NewStyle(nil, nil).Sprint

	fmt.Print(typed("foo"))
	fmt.Println(completed("bar"))
```

What am I missing here?

**Comment by MarvinJWendt** [comment]
Hi, thanks for reporting. It was indeed a bug. 

Quick note: `color` is unreleased and work in progress. Feel free to still use it, but there might be some small breaking changes before the first release.
